name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: Tontico/node-ci-example/ .github/workflows/reusable-workflow.yml@main
    with:
      name: 'Tontico'
      run-tests: true
